title=An ordinary BCU Fork
back=Back
conf=Configuration
confirm=Confirm
w0=This action cannot be undone. Are you sure to delete?
vuni=Unit Gallery
vene=Enemy Gallery
vsta=Stage Menu
vdiy=Custom animations
veff=Effect Gallery
vcas=Castle Gallery
vbgr=Background Gallery
veif=Enemy Finder
vuif=Unit Finder
vmsc=Audio List
bass=Lineup Setting
curr=Continue Battle
sdiy=Level Editor
pcus=Pack List
caic=Sprite Editor
camm=Model Editor
cama=Animation Editor
recg=unit restriction
relr=Level restriction
icon=Icon
icondi=Display Icon
iconde=Deploy Icon
cunt=Unit Manager
ctrt=Trait Manager
backup=Backup Manager
compare=Compare Page
ener=RandomEnemy Manager
unir=RandomUnit Manager
preload=Preload
white=White BG
axis=Show hitboxes
opamin=Minimum opacity
opamax=Maximum opacity
opacity=Opacity
color=Color
accuracy=Accuracy
scale=Scale
fast=Fast
default=Default
quality=Quality
musc=Play music
rllang=Reload language files
rlpks=Reload External Packs
BGvol=Background music volume
SEvol=Sound effects volume
UIvol=Ui effects volume
add=Add
rem=Remove
copy=Copy
link=Redirect
line=Line up
set0=Use
set1=Replace
form=Next form
start=Start
ctop=Change cannon
cmid=Change label
cbas=Change base
orb=Level/Orb
addst=Add stage
addsm=Add map
addl=Add line
reml=Remove line
edit=Edit
extr=Export
revt=Mirror
relo=Reload sprite
saveimg=Save sprite
swcl=Change color
paste=Paste
cpst=Copy stage
dungeon=Quest
replay=Replay
info=Info
cpsm=Copy map
ptst=Paste stage
ptsm=Paste map
rmst=Remove stage
rmsm=Remove map
rema=Remove tree
undo=Undo
redo=Redo
localize=Localize
pack=Packs
enemy=Enemies
unit=Units
forms=Forms
seleanim=Select animation
parent=Parents
selepar=Select parents
save=Save all
import=Import
export=Export
rich=Rich
sniper=Sniper
include=Includes:
exclude=Excludes:
tomax=Maximize Lvl
maxl=Max level
maxp=Max +level
next=Next
prev=Previous
anim=View animation
stage=Stages
combo=Custom Combos
indic=In dictionary
starred=starred
all=Select all
showf=Show filter
ops0=AND operation
ops1=OR operation
ops2=NOR operation
ops3=NAND operation
search=Search
larges=Large screen
pause=Pause
nextf=Next frame
png=Export png
gif=Export gif
expmp4=Export mp4
stat=View data
rply=Replay
load=loading...
error=error occured during loading
item=Items
time=time
zoom=Zoom:
sort=Sort
whiteBG=White BG
blackBG=Black BG
author=Author
savepro=Saving progress... Do not turn off computer
packused=This pack is a parent pack of these packs:
onerow=Layout : one row
tworow=Layout : two rows
rescam=Reset camera
reszom=Reset zoom
preflv=Preferred unit level
addgroup=Add group
addgrouppop=Enter the new group's name
remgroup=Remove group
remgroupconf=Are you sure that you want to remove these groups? This can't be undone
csoul=custom soul
cbge=custom bg effect
soul=souls
corrrea=<html>This entity has corrupted animation data<br>Please reassign animation</html>
reassign=Reassign
reasanim=This cannot be undone. Are you sure to reassign selected animation to this entity?
plusunlock=Unlock plus
levlimoff=0 (Turned Off)
remicon=Remove icon
traitfect=affected by anti-traited
addf=Add form
remcf=Remove form
addc=Add combo
remc=Remove combo
limit=Limit
pcoin=Talents
rempc=Remove talents
meastime=Time Measuring
secs=Seconds
frame=Frames
bspwn=Boss Spawn
advtrt=Advanced Trait-Targetting
maxback=max number of backups
allfile=BC Data
usecombo=Use Pack's CatCombos
packload=Startup Pack Loader
startskip=Skip Loading on Startup
loadpack=Load Pack
jcbac=Enable Backups
backremwarn= oldest backup(s) will be deleted when BCU is closed, will it be fine?
backinfwarn=Backups will be created without any limit, this may affect computer storage in future. Will it be fine?
nobacwarn=Not creating backups won't let you recover your data if it gets corrupted unless you backup manually. Are you sure about this?
btnsnd=Button sound
rawdmg=Display Raw Damage
bgcl0=Sky Up
bgcl1=Sky Down
bgcl2=Ground Up
bgcl3=Ground Down
bgcl4=BG Effect
bgcl5=Overlay Down
bgcl6=Overlay Up
bgcl7=Overlay Alpha
bgeff=BG Effect
bgeff0=Star
bgeff1=Rain
bgeff2=Bubble
bgeff3=Falling Snow
bgeff4=Snow
bgeff5=Snow with Star
bgeff6=Blizzard
bgeff7=Shining
bgeff8=Balloon
bgeff9=Rock
bgeffdum=BG _ Effect
bgjson102=Space Dust
bgjson103=Pink Snow
bgjson110=Unit 13 flying Debris
bgjson117=God Rays
bgjson121=Akuma Rain
bgjson128=Miku Crowd
bgjson132=Collab UFO Cat
bgjson137=Dust Clouds
bgjson141=Water Vapor (BG 141)
bgjson142=Casino (BG 142)
bgjson145=Evil Lair (BG 145)
bgjson148=Snow 2
bgjson153=Sun
bgjson154=Insects
bgjson155=Lightning Bugs
bgjson157=Aku Dimension (BG 157)
bgjson158=Smoke
bgjson159=Aku Dust
bgjson164=Red Moon with Debris
bgjson166=Crowd (BG 166)
bgjson172=Infernal Leaves
bgjson173=Infernal Leaves 2
bgjson174=Infernal Leaves 3
bgjson180=Lab BG Effect (BG 180)
bgjson181=Forest Godrays
bgjson1000=Ember
bgjson1002=Purple Mist 1
bgjson1003=Purple Mist 2
bgjson1004=Purple Mist 3
bgjson1005=Purple Mist and Bubbles
bgjson1006=Purple Mist 5
bgjson1007=Purple Mist 6
bgjson1008=Purple Mist and Big Bang Rocks
none=None
overlay=Overlay
btdly=Unit spawn delay
hue=Hue
sat=Saturation
bri=Brightness
red=Red
gre=Green
blu=Blue
hex=Hex
viewcolor=Viewer Color
viewreset=Reset Viewer Color
savconf=Save Confirmation
savwarn=Do you want to save your work before closing BCU?
genbckp=Generate backup file
dojo=Dojo Stage
usable=Usable Only
excont=Show Followup Stages
groups=Groups
exsts=EX Stages
total=Total
equalprob=Equalize chances
stdis=Show Stage Name
dps=DPS
output=Output
shake=Toggle Shakes in Battle
anypac=Any Pack
pinfo=Extra Pack Information
pdesc=_'s description
sqrwrn=Icon must have the same width and height
sttot=Total Stages:
false=No
true=Yes
any=Any
spatk=Special Attacks
psort0=#pack# (default order)
psort1=#pack# (sort by: name)
psort2=#pack# (sort by: ID)
psort3=#pack# (sort by: #author#)
psort4=#pack# (sort by: BCU version)
psort5=#pack# (sort by: creation date)
psort6=#pack# (sort by: export date)
psort7=#pack# (sort by: enemy amount)
psort8=#pack# (sort by: unit amount)
psort9=#pack# (sort by: stage amount)
cdate=Created:
edate=Released:
ucdate=Unknown Creation Date
uedate=Unknown Export Date
render=Rendering
gameplay=Gameplay
other=Misc.
updatemus=Update Old Music
logs=Error Logs
log=Log
reallv=Simulate BC Leveling
mampm0=ID
mampm1=Parent
mampm2=Sprite
mampm3=Z-Order
mampm4=Position
mampm5=Pivot Point
mampm6=Size
mampm7=Angle
mampm8=Opacity
mampm9=Blending
mampm10=Shear
mampm11=Name
mamgl0=-1: Substract
mamgl1=0: None
mamgl2=1: Add
mamgl3=2: Multiply
mamgl4=3: Screen
maepm0=0 - Parent
maepm1=1 - ID
maepm2=2 - Sprite
maepm3=3 - Z-Order
maepm4=4 - Pos-x
maepm5=5 - Pos-y
maepm6=6 - Pivot-x
maepm7=7 - Pivot-y
maepm8=8 - Scale
maepm9=9 - Width
maepm10=10 - Height
maepm11=11 - Angle
maepm12=12 - Opacity
maepm13=13 - Horizontal Flip
maepm14=14 - Vertical Flip
maepm15=50 - Extend X
maepm16=51 - Extend X (Random Sprite)
maepm17=52 - Extend Y
maepm18=53 - Global Scale
maepm19=54 - Extend Y (Random Sprite)
maepm20=55 - Shear X
maepm21=56 - Shear Y
maapi0=Part ID
maapi1=Modification
maapi2=Loop
maapi3=Name
mape0=Frame
mape1=Value
mape2=Easing
mape3=In/Out
maaea0=None
maaea1=Instant
maaea2=Exponential
maaea3=Polynomial
maaea4=Sinusoidal
maaea5=Elastic
polish=Polish
addfs=Add Start Frames
addvs=Add to Values
trim=Trim
addfav=Add/Remove Selected to Favorites
clrhide=Will be hidden after clearing
ubase=Unit Base
csav=Progression Customizer
urwd=Unit Rewards
pkprog=Simulate Progression
selspeed=Set speed for selected
pkstm=Pack Stage Maps
adreq=Addable Requirement Maps
cureq=Requirement Maps
ulk=Locked Units
plku=Pre-Unlocked Units
grats=Congratulations!
rewardText=You've unlocked _!
formType=the _ form of {UNITNAME}
final=true
unsyncpar=Unsynced Parents
syncpar=Synced Parents
atk=Attack
filter=Filter
defstat=Override BC Stats
searchkey=Search On Type
tolerance=Typo Tolerance
head0=Stage data
head1=Map data
ban0=Ban
ban1=Unban
maxmat=Max material count
addlim=#add# #limit#
remlim=#rem# #limit#
testmode=Test Mode
cleartou=Clear _ to unlock
uclearinf=Unlocked by clearing _
flocked=Forever Locked
smapsch=Chapter Name:
sstgsch=Stage Name:
pinp=Pinpoint
csta=Change Stage
setpref=Set Preferred Lv
rempref=Remove Pref. Lv
htmlprev=Preview HTML
trait=Trait
rarity=Rarity
lvlscale=Level Scaling
maxo=Orb Slots
minfrm=Min form
minlvl=Min level
fixlayer=Fixed Layer
